apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: g.vish1al@gmail.com
    privateKeySecretRef:
      name: vishal-10071999
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx